### ISSUE TITLE
New projects with gradle plugin version >= 0.9.0 are generated without 'gradlew' and  'gradlew.bat'

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-gradle-plugin#11]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2698-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

**TC:**
1. Create new Jmix project ->  choose Jmix version >= 0.9.0  -> choose single-module-application template -> finish

**AR:**
project has been generated without 'gradlew' and  'gradlew.bat' in project tree:
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/93b516ad-7594-4b81-aeb4-33a92b7a27b6)

as a result user can't use a terminal to run commands 'gradlew xxx'

ER:
files should be added to project

**Comment by DartVerder** [comment]
also in gradle\wrapper `gradle-wrapper.jar` file missing

**Comment by alexander-shustanov** [comment]
Was fixed in https://youtrack.cuba-platform.com/issue/JST-1051
