### ISSUE TITLE
Eclipselink enhancements are missing for entities from additional data stores

### ISSUE THREAD

**Issue by soraksh** [Haulmont/jmix-gradle-plugin#12]
Jmix version - '1.0.0-SNAPSHOT'
Plugin version - '0.9.0'

1. Create Jmix project
2. Create one or more additional data stores and some entities for them
3. Run application and try to create or edit such entities

AR:
Entities from additional data stores are not enhanced
```
io.jmix.eclipselink.impl.mapping.EntityNotEnhancedException: 
Entity class Order is missing some of enhancing interfaces:PersistenceObject,PersistenceWeaved,PersistenceWeavedFetchGroups
```

**Comment by DartVerder** [comment]
similar behavior on the latest version
