### ISSUE TITLE
publishToMavenLocal task doesn't work properly

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-gradle-plugin#16]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2888-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC:
create new project>build.gradle
add
'''
tasks.register("publishToMavenLocal") {
}
'''

run ` gradlew clean assemble publishToMavenLocal`
open C:\Users\<username>\.m2\repository\com\company
ER: component should be created in the folder
AR: the target folder is empty

**Comment by andreysubbotin** [comment]
The Gradle plugin doesn't have the task to publish artifacts.
