### ISSUE TITLE
Introduce includePaths param for compileWidgets task

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-gradle-plugin#30]
For the same purpose as https://github.com/Haulmont/jmix-gradle-plugin/issues/8.

### Solution

the `includePaths` param accepts the list of include patterns. For pattern rules see: https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/util/PatternFilterable.html

Example:

```
compileWidgets {
    generate 'com.company.demo.widgets.CustomWidgetSet'
    includePaths('**/io/jmix/**/widget/**', '**/com/company/demo/widgets/**')
}
```

**For QA:**

[jmix-widgets-demo.zip](https://github.com/Haulmont/jmix-gradle-plugin/files/7538518/jmix-widgets-demo.zip)

**NOTE:** Demo project uses plugin **v1.2.0-SNAPSHOT** from maven local. Will be included in plugin v1.1.1

The `./gradlew compileWidgets --info` task is useful for test purposes.

After the initial build, the consequent compilation shouldn't trigger widgetset compilation (except changes in the `com.company.demo.widgets` package), i.e. in the terminal you should see the following:

> Task :compileWidgets UP-TO-DATE

Check the following:
1. changes in the `com.company.demo.widgets` package trigger widgetset compilcation
2. other changes, e.g. in screen controller/descriptor - not

**NOTE:** `includePaths` prevent re-compilation only issued by source code changes. If you see unexpected re-compilation, check the particular reason (execute `compileWidgets` with the `--info` pararm), e.g.:

> Task ':compileWidgets' is not up-to-date because:
  Input property 'sourceFiles' file /Users/gorelov/Developer/jmix-projects/jmix-widgets-demo/src/main/java/com/company/demo/widgets/client/ColorButtonConnector.java has changed.

**Comment by imorenov94** [comment]
**TC2**
Environment:
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3787-212
IntelliJ version: IntelliJ IDEA 2021.2.3 (Ultimate Edition)
**Steps:**
1. Open [zip project](https://github.com/Haulmont/jmix-gradle-plugin/files/7538518/jmix-widgets-demo.zip)
2. Open build.gradle
2. Set up 'version 1.2.0-M2' and bomVersion =  '1.2.0-SNAPSHOT'
3. Navigate to jmix-widgets-demo\src\main\java\com\company\demo\widgets
4. Open ColorButton class and comment this row getState().color = color;
5. Run compileWidgets task

**ER:** compileWidgets task was executed and widget set was re-compiled 
**AR:** compileWidgets task UP-TO-DATE
