### ISSUE TITLE
Enhance kotlin-style accessors for boolean properties

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-gradle-plugin#34]
#### Problem
see https://forum.jmix.ru/t/problema-s-boolean-svojstvami-sushhnostej-v-kotlin/232

Let's assume there is boolean property `isActive` in the persistent entity. 
Kotlin will generate getters and setters with names `isActive()` and `setActive()` instead of `getIsActive()` and `setIsActive()`. 

#### Solution
Support this case during enhancing

#### QA Notes
1. Create a kotlin project
2. Create an entity with a boolean property named, e.g. `isActive`
3. Add browser and editor for this entity
4. Open editor, modify this boolean property only, close editor
 
**ER:** changes in this property should be tracked and saved

**Comment by gorbunkov** [comment]
@dtaimanov please release the gradle plugin and update the plugin version in project templates (jmix-templates). Link templates commits with the current issue.
