### ISSUE TITLE
Enhancing doesn't work for properties with specific names (second uppercase letter in property name) 

### ISSUE THREAD

**Issue by andreysubbotin** [Haulmont/jmix-gradle-plugin#9]
Port cuba-platform/cuba-gradle-plugin#154

**Comment by owlet1997** [comment]
#### Enviroment:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2817-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)
gradle plugin version '0.9.3'

#### TC:
- create new project 
- create entity NewEntity with field aField -> generate getter and setter
- rename getter and setter to `getaField()` and `setaField(String aField)`
- create standard screens for entity
- run app -> open new entity browser -> create

#### AR:
field isn't editable 
![image](https://user-images.githubusercontent.com/45730069/116538608-cbd4aa80-a8f8-11eb-89bf-37718c6515cf.png)
